### ISSUE TITLE
new schema repo

### ISSUE THREAD

**Issue by satra** [dandi/schema#3]
@AlmightyYakob @mgrauer - this is the new schema repo where work will go on from here on out. 

the set of converted dandisets according to the new schema is here: https://www.dropbox.com/sh/2rz0yo73cxycs55/AACI-YVwfHNBfMb8h15v_fF8a?dl=0

**Comment by satra** [comment]
i've updated the json schemas in the repo, and updated the yaml files in the dropbox folder.

**Comment by yarikoptic** [comment]
https://github.com/dandi/dandi-api-datasets/ should have up to date extracts. This repo contains converted from pydantic models in dandi-cli to .json. Closing
