### ISSUE TITLE
Make it into a "dandi_schema" python module?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/schema#9]
which would make it easier (and more formalized) to be used by the dandiarchive and dandi-cli?

Any objections @satra or alternative ideas?

@jwodder could help with this if that would be decided the way forward.

Related: https://github.com/dandi/dandi-cli/issues/101 where we will start using schema for validation

**Comment by satra** [comment]
i would not be opposed to another package, but making the schema handling + validation be part of the dandi package seems ok at this point. we can always break it out later if a need arises.

**Comment by yarikoptic** [comment]
yes, so far boils down to have everything in dandi-cli, so closing here
